// This file is automatically generated by the twpayne/go-xmlstruct package
package aat

// Vocabulary is a struct that maps to the data structure of the Getty AAT vocabulary file.
type Vocabulary struct {
	Subject []struct {
		SubjectID                int `xml:"Subject_ID,attr"`
		AssociativeRelationships *struct {
			AssociativeRelationship []struct {
				ARDate *struct {
					DisplayDate string `xml:"Display_Date"`
					EndDate     int    `xml:"End_Date"`
					StartDate   int    `xml:"Start_Date"`
				} `xml:"AR_Date"`
				HistoricFlag     string `xml:"Historic_Flag"`
				RelatedSubjectID struct {
					VPSubjectID int `xml:"VP_Subject_ID"`
				} `xml:"Related_Subject_ID"`
				RelationshipType string `xml:"Relationship_Type"`
			} `xml:"Associative_Relationship"`
		} `xml:"Associative_Relationships"`
		DescriptiveNotes *struct {
			DescriptiveNote []struct {
				NoteContributors struct {
					NoteContributor []struct {
						ContributorID string `xml:"Contributor_id"`
					} `xml:"Note_Contributor"`
				} `xml:"Note_Contributors"`
				NoteLanguage string `xml:"Note_Language"`
				NoteSources  *struct {
					NoteSource []struct {
						Source struct {
							SourceID string `xml:"Source_ID"`
						} `xml:"Source"`
					} `xml:"Note_Source"`
				} `xml:"Note_Sources"`
				NoteText string `xml:"Note_Text"`
			} `xml:"Descriptive_Note"`
		} `xml:"Descriptive_Notes"`
		Hierarchy           string `xml:"Hierarchy"`
		MergedStatus        string `xml:"Merged_Status"`
		ParentRelationships struct {
			NonPreferredParent []struct {
				HierRelType  string `xml:"Hier_Rel_Type"`
				HistoricFlag string `xml:"Historic_Flag"`
				ParentDate   *struct {
					DisplayDate string `xml:"Display_Date"`
					EndDate     int    `xml:"End_Date"`
					StartDate   int    `xml:"Start_Date"`
				} `xml:"Parent_Date"`
				ParentString     string `xml:"Parent_String"`
				ParentSubjectID  int    `xml:"Parent_Subject_ID"`
				RelationshipType string `xml:"Relationship_Type"`
			} `xml:"Non-Preferred_Parent"`
			PreferredParent struct {
				HierRelType  string `xml:"Hier_Rel_Type"`
				HistoricFlag string `xml:"Historic_Flag"`
				ParentDate   *struct {
					DisplayDate string `xml:"Display_Date"`
					EndDate     int    `xml:"End_Date"`
					StartDate   int    `xml:"Start_Date"`
				} `xml:"Parent_Date"`
				ParentString     string `xml:"Parent_String"`
				ParentSubjectID  int    `xml:"Parent_Subject_ID"`
				RelationshipType string `xml:"Relationship_Type"`
			} `xml:"Preferred_Parent"`
		} `xml:"Parent_Relationships"`
		RecordType          string `xml:"Record_Type"`
		SortOrder           int    `xml:"Sort_Order"`
		SubjectContributors struct {
			SubjectContributor []struct {
				ContributorID string `xml:"Contributor_id"`
			} `xml:"Subject_Contributor"`
		} `xml:"Subject_Contributors"`
		SubjectSources *struct {
			SubjectSource []struct {
				Source struct {
					SourceID string `xml:"Source_ID"`
				} `xml:"Source"`
			} `xml:"Subject_Source"`
		} `xml:"Subject_Sources"`
		Terms struct {
			NonPreferredTerm []struct {
				DisplayName      string `xml:"Display_Name"`
				HistoricFlag     string `xml:"Historic_Flag"`
				TermContributors struct {
					TermContributor []struct {
						ContributorID string `xml:"Contributor_id"`
						Preferred     string `xml:"Preferred"`
					} `xml:"Term_Contributor"`
				} `xml:"Term_Contributors"`
				TermID        int `xml:"Term_ID"`
				TermLanguages *struct {
					TermLanguage []struct {
						LangStat     string `xml:"Lang_Stat"`
						Language     string `xml:"Language"`
						PartOfSpeech string `xml:"Part_of_Speech"`
						Preferred    string `xml:"Preferred"`
						Qualifier    string `xml:"Qualifier"`
						TermType     string `xml:"Term_Type"`
					} `xml:"Term_Language"`
				} `xml:"Term_Languages"`
				TermSources *struct {
					TermSource []struct {
						Page      string `xml:"Page"`
						Preferred string `xml:"Preferred"`
						Source    struct {
							SourceID string `xml:"Source_ID"`
						} `xml:"Source"`
					} `xml:"Term_Source"`
				} `xml:"Term_Sources"`
				TermText   string `xml:"Term_Text"`
				Vernacular string `xml:"Vernacular"`
			} `xml:"Non-Preferred_Term"`
			PreferredTerm struct {
				DisplayName      string `xml:"Display_Name"`
				HistoricFlag     string `xml:"Historic_Flag"`
				TermContributors struct {
					TermContributor []struct {
						ContributorID string `xml:"Contributor_id"`
						Preferred     string `xml:"Preferred"`
					} `xml:"Term_Contributor"`
				} `xml:"Term_Contributors"`
				TermID        int `xml:"Term_ID"`
				TermLanguages struct {
					TermLanguage []struct {
						LangStat     string `xml:"Lang_Stat"`
						Language     string `xml:"Language"`
						PartOfSpeech string `xml:"Part_of_Speech"`
						Preferred    string `xml:"Preferred"`
						Qualifier    string `xml:"Qualifier"`
						TermType     string `xml:"Term_Type"`
					} `xml:"Term_Language"`
				} `xml:"Term_Languages"`
				TermSources *struct {
					TermSource []struct {
						Page      string `xml:"Page"`
						Preferred string `xml:"Preferred"`
						Source    struct {
							SourceID string `xml:"Source_ID"`
						} `xml:"Source"`
					} `xml:"Term_Source"`
				} `xml:"Term_Sources"`
				TermText   string `xml:"Term_Text"`
				Vernacular string `xml:"Vernacular"`
			} `xml:"Preferred_Term"`
		} `xml:"Terms"`
	} `xml:"Subject"`
}
